FROM denoland/deno:alpine

# Set working directory inside the container
WORKDIR /app

# Copy package files
COPY package.json ./

# Install dependencies and cache installed packages
RUN deno install

# Copy rest of the source code
COPY . .

# Expose Vite dev server port
EXPOSE 5173

# Run Vite in dev mode, accessible outside the container
CMD ["deno", "task", "dev"]