DROP TABLE IF EXISTS users;

DROP TABLE IF EXISTS devices;

DROP TABLE IF EXISTS device_user;

DROP TABLE IF EXISTS habit_rules;

DROP TABLE IF EXISTS pet_states;

DROP TABLE IF EXISTS activity_events;

DROP EXTENSION IF EXISTS timescaledb;